const bestPracticeRules = [
  {
    id: 'bp_001',
    category: 'bestPractice',
    severity: 'LOW',
    languages: ['javascript', 'typescript'],
    title: 'var keyword used instead of const/let',
    description: 'var has function scope and is hoisted, causing subtle bugs where variables are accessible outside their intended block. This is a known source of closure bugs in loops and async code.',
    pattern: /\bvar\s+\w+/g,
    suggestedFix: 'Use const for values that do not change, let for variables that do. Never use var in modern JavaScript.',
  },
  {
    id: 'bp_002',
    category: 'bestPractice',
    severity: 'MEDIUM',
    languages: ['javascript', 'typescript'],
    title: 'Loose equality operator used',
    description: 'The == operator performs type coercion before comparing, leading to infamous JavaScript gotchas: 0 == false is true, \"\" == 0 is true, null == undefined is true. These cause subtle logic bugs.',
    pattern: /[^=!<>]==[^=]|[^=!<>]!=[^=]/g,
    suggestedFix: 'Always use === (strict equality) and !== (strict inequality). This compares both value and type with no coercion.',
  },
  {
    id: 'bp_003',
    category: 'bestPractice',
    severity: 'MEDIUM',
    languages: ['javascript', 'typescript'],
    title: 'Promise .then() without .catch() handler',
    description: 'A Promise chain without a .catch() handler creates an unhandled promise rejection. In Node.js, unhandled rejections terminate the process. In browsers, they fail silently and cause bugs.',
    pattern: /\.then\s*\([^)]*\)(?!\s*\.catch)/g,
    suggestedFix: 'Always append .catch(err => { /* handle */ }) to promise chains, or use async/await with try/catch blocks.',
  },
  {
    id: 'bp_004',
    category: 'bestPractice',
    severity: 'LOW',
    languages: ['python'],
    title: 'print() statement in production code',
    description: 'print() statements are a debugging artifact. In production, they write to stdout uncontrolled, expose internal state, and cannot be toggled by log level or redirected to log aggregators.',
    pattern: /\bprint\s*\(/g,
    suggestedFix: "Replace with Python's logging module: import logging; logging.info('message'). Configure log levels via environment.",
  },
  {
    id: 'bp_005',
    category: 'bestPractice',
    severity: 'HIGH',
    languages: ['python'],
    title: 'Mutable default argument in function definition',
    description: 'Using a mutable object (list or dict) as a default argument is a classic Python bug. The default is created ONCE when the function is defined, not on each call. Mutations persist across calls, creating shared state bugs.',
    pattern: /def\s+\w+\s*\([^)]*=\s*[\[\{][^)]*\)/g,
    suggestedFix: 'Use None as default and create inside the function: def func(items=None): items = items if items is not None else []',
  },
];

export default bestPracticeRules;
