const performanceRules = [
  {
    id: 'perf_001',
    category: 'performance',
    severity: 'HIGH',
    title: 'Nested loop detected — potential O(n²) complexity',
    description: 'Nested loops multiply execution time. For n=1000 items, this runs 1,000,000 iterations. At n=10,000 it runs 100,000,000.',
    pattern: /for\s*\([^)]*\)\s*\{[^}]*for\s*\([^)]*\)/gs,
    suggestedFix: 'Consider flattening with a hash map for O(n) lookup, or restructure the algorithm to avoid the inner loop.',
  },
  {
    id: 'perf_002',
    category: 'performance',
    severity: 'MEDIUM',
    title: 'Infinite loop pattern detected',
    description: 'while(true) loops must have a guaranteed break condition. Missing or unreachable break statements cause the process to hang indefinitely.',
    pattern: /while\s*\(\s*true\s*\)|while\s*\(\s*1\s*\)/g,
    suggestedFix: 'Ensure a clear break or return condition. Consider using a counter limit as a safety valve: let i = 0; while(condition && i++ < MAX_ITER)',
  },
  {
    id: 'perf_003',
    category: 'performance',
    severity: 'HIGH',
    title: 'DOM query inside loop',
    description: 'Calling document.getElementById or querySelector inside a loop causes the browser to re-traverse the entire DOM on every iteration. This is exponentially slow for large DOM trees.',
    pattern: /for\s*\([^)]*\)\s*\{[^}]*document\.(getElementById|querySelector|getElementsBy)/gs,
    suggestedFix: 'Cache the DOM reference before the loop: const el = document.getElementById(\'id\'); Then use el inside the loop.',
  },
  {
    id: 'perf_004',
    category: 'performance',
    severity: 'LOW',
    title: 'console.log statements found',
    description: 'Console statements left in production code expose internal state and logic to anyone with DevTools open. They also accumulate in memory and slow down high-frequency code paths.',
    pattern: /console\.(log|warn|error|info|debug)\s*\(/g,
    suggestedFix: 'Remove all console statements before deployment. Use a proper logger (winston, pino) with log levels that can be disabled in production via environment config.',
  },
  {
    id: 'perf_005',
    category: 'performance',
    severity: 'HIGH',
    title: 'Synchronous fs call blocks event loop',
    description: 'Synchronous fs methods block Node.js\'s single-threaded event loop entirely while the disk operation completes. Under load, this prevents the server from handling any other requests.',
    pattern: /fs\.(readFileSync|writeFileSync|appendFileSync|existsSync|mkdirSync|readdirSync)\s*\(/g,
    suggestedFix: 'Use the async equivalents: fs.readFile(), fs.promises.readFile(), or the fs/promises module with async/await.',
  },
  {
    id: 'perf_006',
    category: 'performance',
    severity: 'LOW',
    title: 'Potentially expensive object creation on every render',
    description: 'Creating new arrays or objects inline in frequently-called functions (like React render methods) allocates new memory on every call, increasing GC pressure.',
    pattern: /\[\s*\]\.filter\s*\(|new\s+Array\s*\(|new\s+Object\s*\(/g,
    suggestedFix: 'Hoist static arrays/objects outside the function, or use useMemo() in React to memoize expensive computations.',
  },
  {
    id: 'perf_007',
    category: 'performance',
    severity: 'MEDIUM',
    title: 'setTimeout called inside loop',
    description: 'Scheduling many setTimeout calls inside a loop floods the event queue and causes unpredictable timing. Each callback competes for execution, creating jitter and memory pressure.',
    pattern: /for\s*\([^)]*\)\s*\{[^}]*setTimeout/gs,
    suggestedFix: 'Batch operations with a single timer, use requestAnimationFrame for visual updates, or restructure to process items sequentially with async/await.',
  },
];

export default performanceRules;
