const securityRules = [
  {
    id: 'sec_001',
    category: 'security',
    severity: 'CRITICAL',
    title: 'Dangerous eval() call detected',
    description: 'eval() executes arbitrary strings as code, creating a direct vector for code injection attacks. Any user-controlled data passed to eval() gives attackers full code execution in the browser or Node.js runtime.',
    pattern: /eval\s*\(/g,
    impact: 'Remote code execution, data theft, complete application compromise.',
    suggestedFix: 'Replace with JSON.parse() for data, or use a function map for dynamic dispatch. Never pass user input to eval().',
    languages: ['javascript', 'typescript'],
  },
  {
    id: 'sec_002',
    category: 'security',
    severity: 'HIGH',
    title: 'XSS risk via innerHTML assignment',
    description: 'Assigning to innerHTML parses the string as HTML, which executes any <script> tags or event handlers embedded within. If the string contains any user input, this is a Cross-Site Scripting (XSS) vulnerability.',
    pattern: /\.innerHTML\s*=/g,
    impact: 'Attackers can steal session cookies, perform actions as the user, or redirect to malicious sites.',
    suggestedFix: 'Use textContent for plain text, or sanitize with DOMPurify before assigning to innerHTML.',
    languages: ['javascript', 'typescript'],
  },
  {
    id: 'sec_003',
    category: 'security',
    severity: 'HIGH',
    title: 'Insecure document.write() usage',
    description: 'document.write() can inject arbitrary HTML into the page and is frequently used as an XSS attack vector. It also blocks the HTML parser and degrades performance.',
    pattern: /document\.write\s*\(/g,
    impact: 'HTML injection, XSS, and severe rendering performance degradation.',
    suggestedFix: 'Use DOM manipulation methods like createElement() and appendChild() instead.',
    languages: ['javascript', 'typescript'],
  },
  {
    id: 'sec_004',
    category: 'security',
    severity: 'HIGH',
    title: 'Sensitive token stored in localStorage',
    description: 'Storing authentication tokens in localStorage exposes them to any JavaScript running on the page, including third-party scripts and XSS payloads. localStorage has no same-origin token security.',
    pattern: /localStorage\.setItem\s*\(\s*['"`][^'"`]*(token|auth|jwt|session|key)[^'"`]*['"`]/gi,
    impact: 'Token theft via XSS, leading to account takeover.',
    suggestedFix: 'Store tokens in httpOnly, Secure, SameSite=Strict cookies managed server-side. Never store JWTs in localStorage.',
    languages: ['javascript', 'typescript'],
  },
  {
    id: 'sec_005',
    category: 'security',
    severity: 'CRITICAL',
    title: 'Insecure deserialization via pickle',
    description: 'pickle.load() deserializes arbitrary Python objects. A malicious pickle payload can execute arbitrary code during deserialization. Never deserialize untrusted data with pickle.',
    pattern: /pickle\.loads?\s*\(/g,
    impact: 'Remote code execution, full server compromise.',
    suggestedFix: 'Use JSON for data exchange. If pickle is required, cryptographically sign payloads and verify before deserializing.',
    languages: ['python'],
  },
  {
    id: 'sec_006',
    category: 'security',
    severity: 'CRITICAL',
    title: 'Command injection risk via shell execution',
    description: 'Passing unsanitized input to os.system() or subprocess with shell=True allows attackers to inject arbitrary shell commands by embedding metacharacters like semicolons, pipes, or backticks.',
    pattern: /os\.system\s*\(|subprocess\.(run|call|Popen)\s*\([^)]*shell\s*=\s*True/g,
    impact: 'Full server compromise, data exfiltration, ransomware deployment.',
    suggestedFix: 'Use subprocess.run() with a list argument and shell=False. Validate and whitelist all inputs before use in system calls.',
    languages: ['python'],
  },
  {
    id: 'sec_007',
    category: 'security',
    severity: 'CRITICAL',
    title: 'SQL injection via string concatenation',
    description: 'Building SQL queries by concatenating user input bypasses all database security. An attacker can manipulate the query structure to extract, modify, or delete any data in the database.',
    pattern: /["'`]\s*SELECT\s+.+\s+WHERE\s+.+["'`]\s*\+|["'`]\s*INSERT\s+INTO\s*.+\+|["'`]\s*UPDATE\s+.+SET\s+.+\+|["'`]\s*DELETE\s+FROM\s+.+\+/gi,
    impact: 'Complete database compromise, authentication bypass, data exfiltration.',
    suggestedFix: "Use parameterized queries or prepared statements. Example: db.query('SELECT * FROM users WHERE id = ?', [userId])",
    languages: 'all',
  },
  {
    id: 'sec_008',
    category: 'security',
    severity: 'CRITICAL',
    title: 'Hardcoded secret or credential detected',
    description: 'Hardcoding secrets, API keys, or passwords in source code exposes them to anyone with repository access - including public GitHub repos. Secrets in code are frequently harvested by automated scanners.',
    pattern: /(API_KEY|SECRET_KEY|PASSWORD|ACCESS_TOKEN|PRIVATE_KEY|CLIENT_SECRET)\s*=\s*['"`][^'"`]{6,}['"`]/gi,
    impact: 'Credential theft, unauthorized API access, financial charges, data breach.',
    suggestedFix: 'Move all secrets to environment variables. Use process.env.KEY_NAME in Node.js, os.getenv(\'KEY_NAME\') in Python. Use .env files with .gitignore.',
    languages: 'all',
  },
  {
    id: 'sec_009',
    category: 'security',
    severity: 'HIGH',
    title: 'Dangerous exec() call',
    description: 'exec() compiles and executes arbitrary Python code at runtime. Like eval(), any user-controlled data reaching exec() gives attackers code execution capability on your server.',
    pattern: /\bexec\s*\(/g,
    impact: 'Remote code execution, full server compromise.',
    suggestedFix: 'Eliminate exec() usage. Use explicit function calls, importlib for dynamic imports, or a sandboxed environment for user-provided code.',
    languages: ['python'],
  },
  {
    id: 'sec_010',
    category: 'security',
    severity: 'HIGH',
    title: 'SSL/TLS certificate verification disabled',
    description: 'Disabling certificate verification removes protection against man-in-the-middle attacks. Any network traffic to external services can be intercepted and modified by attackers on the same network.',
    pattern: /verify\s*=\s*False|rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"`]0['"`]/gi,
    impact: 'Man-in-the-middle attacks, credential interception, data tampering.',
    suggestedFix: 'Never disable SSL verification in production. Fix the underlying certificate issue instead. Use proper CA certificates.',
    languages: 'all',
  },
];

export default securityRules;
